var p1 = document.getElementById("first");
var p2 = document.getElementsByClassName("special");
var p3 = document.querySelector("p");
var p4 = document.querySelector("#first");
var p5 = document.querySelector(".special");
var p6 = document.querySelectorAll(".special");
var p7 = document.getElementsByTagName("p");
var p8 = document.querySelector("h1 +p");
var p9 = document.querySelectorAll("p");
var p10 = document.querySelectorAll("#first");
console.log(p1);
console.log(p2[0]);
console.log(p3);
console.log(p4);
console.log(p5);
console.log(p6[0]);
console.log(p7[0]);
console.log(p8);
console.log(p9[0]);
console.log(p10[0]);